@startuml
title Dashboard Command - Sequence Diagram

participant Logic
create ":DashboardCommand" as DC
participant "<<class>>\nDashboardUi" as DUi
participant "<<class>>\nInternshipList" as IL

Logic -> DC** : create Dashboard Command
activate DC
return

Logic -> DC : execute
activate DC

DC -> DUi : print dashboard
activate DUi

DUi -> IL : get internship info
activate IL
IL --> DUi : return info
deactivate IL

DUi --> DC
deactivate DUi

DC --> Logic
deactivate DC
@enduml