@startuml
title Delete Command - Sequence Diagram

participant ":InternityManager" as Logic
participant ":DeleteCommand" as DC
participant "<<class>>\nInternshipList" as IL
participant "<<class>>\nUi" as UI



Logic -> DC: execute()
activate DC

DC -> IL: get(index)
activate IL
IL --> DC: return Internship
deactivate IL

DC -> IL: delete(index)
activate IL

IL --> DC
deactivate IL

DC -> UI: printRemoveInternship()
activate UI
UI --> DC
deactivate UI


DC --> Logic
deactivate DC

@enduml