@startuml
title Delete Command - Sequence Diagram

participant Logic
create ":DeleteCommand" as DC
participant "<<class>>\nInternshipList" as IL
participant ":Internship" as Intern
participant "<<class>>\nUi" as UI

Logic -> DC**: new DeleteCommand(index)
activate DC
return (created)
deactivate DC

Logic -> DC: execute()
activate DC

DC -> IL: get(index)
activate IL
IL -> Intern: retrieve internship
activate Intern
Intern --> IL: return internship
deactivate Intern
IL --> DC: return internship
deactivate IL

DC -> IL: delete(index)
activate IL
IL -> IL:  remove internship
activate IL
IL --> IL
deactivate IL
IL --> DC
deactivate IL

DC -> UI: printRemoveInternship()
activate UI
UI --> DC
deactivate UI


DC --> Logic
deactivate DC

@enduml