@startuml
title Find Command - Sequence Diagram

participant Logic
participant ":FindCommand" as FC
participant "<<class>>\nInternshipList" as IL
participant ":Internship" as IN
participant "<<class>>\nUi" as Ui

Logic -> FC**: new FindCommand(...)
activate FC
return (created)

Logic -> FC: execute()
activate FC

FC -> IL: findInternship(...)
activate IL

loop for each internship in list
    IL -> IN: get company and role
    activate IN
    IN --> IL: return company and role
    deactivate IN
    opt company or role contains keyword
        IL -> IL: add internship to an ArrayList\nof matching internships
        activate IL
        IL --> IL: return
        deactivate IL
    end
end

IL -> Ui: print matching internships
activate Ui
Ui --> IL
deactivate Ui

IL --> FC
deactivate IL

FC --> Logic
deactivate FC

@enduml
