@startuml ModelComponentCD
hide circle
title Model Component - Class Diagram
left to right direction
skinparam classAttributeIconSize 0


class InternshipList {
  - {static} storage: Storage
  - {static} username: String
  + {static} setStorage(Storage): void
  + {static} loadFromStorage(): void
  + {static} saveToStorage(): void
  + {static} size(): int
  + {static} sortInternships(orderType): void
  + {static} listAll(orderType): void
  + {static} findInternship(String): void
  + {static} clear(): void
  - {static} isEmpty(): boolean
}

class "<<interface>>\nComparable<T>" {
    + compareTo(T): int
}

class Internship {
  - company: String
  - role: String
  - status: String
  - pay: int
  + Internship(String, String, Date, int)
  + {static} isValidStatus(String): boolean
  + compareTo(Internship): int
  + toString(): String
}

class Date {
  - day: int
  - month: int
  - year: int
  + Date(int, int, int)
  + compareTo(Date): int
  + toString(): String
}


InternshipList *-- "*" Internship
Internship .|> "<<interface>>\nComparable<T>"
Date .left.|> "<<interface>>\nComparable<T>"
Internship -right-> "1" Date : due by >



@enduml
