@startuml
title Storage Load Operation - Main Sequence

participant ":InternityManager" as IM
participant "<<class>>\nInternshipList" as IL
participant ":Storage" as S

IM -> IL: load from storage
activate IL

IL -> S: load
activate S

ref over S
    Check Storage File
end ref

alt file does not exist
    S --> IL: return empty ArrayList
else file exists
    ref over S
        Parse Header and Username
    end ref

    ref over S
        Parse Internship Lines
    end ref
end

S --> IL: return ArrayList<Internship>
deactivate S

IL -> IL: clear current list
activate IL
IL --> IL
deactivate IL
IL -> IL: add all loaded internships
activate IL
IL --> IL
deactivate IL

IL --> IM
deactivate IL

@enduml
